parameters:
    database_driver:   pdo_mysql
    database_host:     %database.host%
    database_port:     %database.port%
    database_name:     pairfony
    database_user:     %database.user%
    database_password: %database.password%

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    github_client_id:     %github.client.id%
    github_client_secret: %github.client.secret%
